<?xml version='1.0' encoding='ISO-8859-1' standalone= "no" ?>


<!DOCTYPE repairs [
  
<!ELEMENT repairs (client*)>
<!ATTLIST client type CDATA #IMPLIED>

<!ELEMENT client (name?, details*, location?, contact?)>

<!ELEMENT name (title?, first_name+, surname)>

<!ELEMENT details (date_of_repair+, cost_of_repair
,repair_issue+, trade_person+) > 

<!ELEMENT trade_person (trade+, number*)>
<!ATTLIST trade_person name CDATA #IMPLIED>

<!ELEMENT location (Eircode?, street?, town?, city?)><!ATTLIST location proximity CDATA #IMPLIED> 

<!ELEMENT contact (email*, client_number*)> 

<!ELEMENT title (#PCDATA)> 
<!ELEMENT first_name (#PCDATA)> 
<!ELEMENT surname (#PCDATA)>

<!ELEMENT date_of_repair (#PCDATA)>
<!ELEMENT cost_of_repair (#PCDATA)>
<!ELEMENT repair_issue (#PCDATA)>
<!ELEMENT trade (#PCDATA)>
<!ELEMENT number (#PCDATA)>

<!ELEMENT Eircode (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT town (#PCDATA)>
<!ELEMENT city (#PCDATA)>

<!ELEMENT email (#PCDATA)>
<!ELEMENT client_number (#PCDATA)>

]>

<repairs>
 
<client type= "Domestic"> <!--type tells us if it's domestic or business -->

 <!--  more information on the name -->
    <name>
        <title> Mr. </title> 
        <first_name> Luke </first_name>
        <surname> Seckerson </surname>
    </name>
    
     <!-- Main bulk of 'repairs' can have multiple repairs -->
    <details>
        <date_of_repair> 12/3/2019</date_of_repair>
        <cost_of_repair> 30.00 </cost_of_repair>
        <repair_issue> Broken Boiler </repair_issue>
        <trade_person name = "Peter"> 
            <trade> Plumber </trade>
            <number> 087-394-8789 </number>
        </trade_person>
    </details>
    
    <!-- location, different prices depending on location -->
    <location proximity = "close">
         <Eircode> A61C3FE </Eircode>
         <street> random Street </street> 
         <town> Dundalk </town>
         <city> </city>
    </location>
    
    <!-- stores all the contact info available to contact client about repairs -->

    <contact>
    <!--  email is indented like that for correct nesting -->

        <email status = "subscribed">
         l.seckerson@gmail.com 
         </email>
        <client_number> 086-111-2345 </client_number>
        <Eircode> A61C3FE </Eircode>
    </contact>
</client>

<!--  new client -->

<client type = "Business"> 
    <name> 
        <title> Dr. </title>
        <first_name> Rachel </first_name>
        <surname> Powell </surname>
    </name>
    
    <details>
        <cost_of_repair> 210.23 </cost_of_repair>
        <date_of_repair> 11/11/2020 </date_of_repair>
        <repair_issue> Leaky pipes </repair_issue>
        <trade_person name = "Bob"> 
            <number> </number>
            <trade> Plumber </trade>
        </trade_person>
    </details>
    
    <details>
        <cost_of_repair> 140.03 </cost_of_repair>
        <date_of_repair> 29/11/2020 </date_of_repair>
        <repair_issue> Faulty Electrics </repair_issue>
        <trade_person> 
            <number> 087-232-3234 </number>
            <trade> Electrican </trade>
        </trade_person>
    </details>
    
    <location proximity = "Far"> 
        <Eircode> A87DE32 </Eircode>
        <street> doctor's road </street>
        <town> </town>
        <city> Dublin </city>
    </location>
      
    <contact> 
         <email type = "business">
         doctor@clinic
         </email>
         <email type = "personal">
         powell@gmail.com
         </email> 
         <client_number type = "mobile">
          087-321-2345
         </client_number>                 
    </contact>
     
</client>
</repairs>

