<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE BusinessCustomer_info
[<!ELEMENT BusinessCustomer_info (BusinessCustomer*)>
 <!ELEMENT BusinessCustomer (Customer, sizeOfBusiness, meterTypeElectricity, meterTypeGas, billFrequency, businessName, businessLocation)>
 <!ELEMENT Customer (Customer.accountNumber, Customer.email, Customer.mprn, Customer.contactNumber)>
 <!ATTLIST Customer IBAN CDATA #REQUIRED>
 <!ELEMENT Customer.accountNumber (#PCDATA)>
 <!ELEMENT Customer.email (#PCDATA)>
 <!ELEMENT Customer.mprn (#PCDATA)>
 <!ELEMENT Customer.contactNumber (#PCDATA)>
 <!ELEMENT sizeOfBusiness (#PCDATA)>
 <!ELEMENT meterTypeElectricity (#PCDATA)>
 <!ELEMENT meterTypeGas (#PCDATA)>
 <!ELEMENT billFrequency (#PCDATA)>
 <!ELEMENT businessName (#PCDATA)>
 <!ELEMENT businessLocation (street+, city, county)>
 <!ELEMENT street (#PCDATA)>
 <!ELEMENT city (#PCDATA)>
 <!ELEMENT county (#PCDATA)>
]>
<BusinessCustomer_info>
  <BusinessCustomer>?
    <Customer IBAN="IE9876AIB987654674">
      <Customer.accountNumber>1123456790</Customer.accountNumber>
      <Customer.email>Argos.Dalkey@email.com</Customer.email>
      <Customer.mprn>09439593201</Customer.mprn>
      <Customer.contactNumber>0334325876</Customer.contactNumber>
    </Customer>
    <sizeOfBusiness>medium</sizeOfBusiness>
    <meterTypeElectricity>standard</meterTypeElectricity>
    <meterTypeGas>standard</meterTypeGas>
    <billFrequency>monthly</billFrequency>
    <businessName>Argos</businessName>
    <businessLocation>
      <street>45 Castle st Dalkey</street>
      <city>Dalkey</city>
      <county>Dublin</county>
    </businessLocation>
  </BusinessCustomer>
</BusinessCustomer_info>