<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE DomesticCustomer_info
[<!ELEMENT DomesticCustomer_info (DomesticCustomer*)>
 <!ELEMENT DomesticCustomer (Customer, paperlessBilling, unmissableRewards, customerName, homeAddress)>
 <!ELEMENT Customer (Customer.accountNumber, Customer.email, Customer.mprn, Customer.contactNumber)>
 <!ATTLIST Customer IBAN CDATA #REQUIRED>
 <!ELEMENT Customer.accountNumber (#PCDATA)>
 <!ELEMENT Customer.email (#PCDATA)>
 <!ELEMENT Customer.mprn (#PCDATA)>
 <!ELEMENT Customer.contactNumber (#PCDATA)>
 <!ELEMENT paperlessBilling (#PCDATA)>
 <!ELEMENT unmissableRewards (#PCDATA)>
 <!ELEMENT customerName (title?, firstname+, surname)>
 <!ELEMENT title (#PCDATA)>
 <!ELEMENT firstName (#PCDATA)>
 <!ELEMENT surname (#PCDATA)>
 <!ELEMENT homeAddress (street+, city, county)>
 <!ELEMENT street (#PCDATA)>
 <!ELEMENT city (#PCDATA)>
 <!ELEMENT county (#PCDATA)>
 
]>
<DomesticCustomer_info>
  <DomesticCustomer>
    <Customer IBAN="IE1234AIB123432432">
      <Customer.accountNumber>123345567</Customer.accountNumber>
      <Customer.email>johnWill@email.com</Customer.email>
      <Customer.mprn>12345678911</Customer.mprn>
      <Customer.contactNumber>0018532123</Customer.contactNumber>
    </Customer>
    <paperlessBilling>true</paperlessBilling>
    <unmissableRewards>true</unmissableRewards>
    <customerName>
      <title>Mr</title>
      <firstName>John</firstName>
      <surname>Will</surname>
    </customerName>
    <homeAddress>
      <street>Kilsheelan</street>
      <city>Clonmel</city>
      <county>Tipperary</county>
    </homeAddress>
  </DomesticCustomer>
</DomesticCustomer_info>