<?xml version='1.0' encoding='ISO-8859-1' standalone= "no" ?>



<!DOCTYPE account [
  
<!ELEMENT home_energy (customer*)>

<!ELEMENT customer (name, payment_plan, discount?)>

<!ELEMENT name (title?, first_name+, surname)>

<!ELEMENT payment_plan (length_of_contract, estimated_annual_bill, estimated_monthly_bill?, contract_dates, 
early_exit_fee?)>
<!ATTLIST payment_plan type CDATA #IMPLIED> 
<!ATTLIST estimated_montly_bill currency CDATA #IMPLIED> 
<!ATTLIST estimated_annual_bill currency CDATA #IMPLIED> 

<!ELEMENT contract_dates (contract_start_date, contract_end_date)>


<!ELEMENT discount (discount_percentage*, length_of_discount*)>   
<!ATTLIST discount status CDATA #IMPLIED> 
  
<!ELEMENT title (#PCDATA)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>

<!ELEMENT length_of_contract (#PCDATA)>
<!ELEMENT estimated_annual_bill (#PCDATA)>
<!ELEMENT estimated_monthly_bill (#PCDATA)>
<!ELEMENT contract_start_date (#PCDATA)>
<!ELEMENT contract_end_date (#PCDATA)>
<!ELEMENT early_exit_fee (#PCDATA)>

<!ELEMENT discount_percentage (#PCDATA)>
<!ELEMENT length_of_discount (#PCDATA)>  

  
  
]>


<home_energy> 

<customer>

<!--  need to link to customer class (association) -->
    <name> 
        <title>Mr. </title>
        <first_name> Luke </first_name>
        <surname>Seckerson</surname>
     </name>

    <payment_plan type = "Electricy Saving's plan">
        <length_of_contract > 
        1 Year 
        </length_of_contract>
        <estimated_annual_bill currency = "euro">
         550.32
        </estimated_annual_bill>
        <estimated_monthly_bill currency = "euro">
         46.23
        </estimated_monthly_bill>
        <contract_dates> 
            <contract_start_date>
            1/2/2019
            </contract_start_date>
            <contract_end_date>
            1/2/2020
            </contract_end_date>
        </contract_dates>
        <early_exit_fee> 
          100.00 
        </early_exit_fee>
    </payment_plan>    
    
       <discount status = "applied"> 
            <discount_percentage> 
            2.2% 
            </discount_percentage>
            <length_of_discount>
             2 months
             </length_of_discount>
       </discount>
    
</customer>

<customer>

<!--  need to link to customer class (association) -->
    <name> 
        <title>Ms. </title>
        <first_name> Samus </first_name>
        <surname>Aran</surname>
     </name>

    <payment_plan type = "Dual Fuel Plan">
        <length_of_contract > 
        3 Year 
        </length_of_contract>
        <estimated_annual_bill currency = "euro">
         990.32
        </estimated_annual_bill>
        <estimated_monthly_bill currency = "euro">
         88.90
        </estimated_monthly_bill>
        <contract_dates> 
            <contract_start_date>
            23/5/2019
            </contract_start_date>
            <contract_end_date>
            24/5/2022
            </contract_end_date>
        </contract_dates>
        <early_exit_fee> 
          500.00 
        </early_exit_fee>
    </payment_plan>    
    
       <discount status = "applied"> 
            <discount_percentage> 
            5.7% 
            </discount_percentage>
            <length_of_discount>
             6 months
             </length_of_discount>
       </discount>
</customer> 

</home_energy>